<?php

/**
 * @file
 * Implement module file
 */

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 *
 * @param EntityTypeInterface $entity_type
 * @return array
 */
function jsonapi_enhance_entity_entity_base_field_info(EntityTypeInterface $entity_type) {
  return [
    'entity_link' => BaseFieldDefinition::create('string')
      ->setLabel(t('Edit URL'))
      ->setDescription(t('URL for edit entity'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\jsonapi_enhance_entity\Field\JsonApiEditEntityUrl')
  ];
}